apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "alfresco-adf-app.fullname" . }}
  labels:
    app: {{ template "alfresco-adf-app.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "alfresco-adf-app.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.registryPullSecrets }}
      # only set this secret if a private docker registry variable is defined
      imagePullSecrets:
        - name: {{ .Values.registryPullSecrets }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}{{ if .Values.image.tag }}:{{ .Values.image.tag }}{{- end}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{if ne .Values.ingress.path "/"}}
          - name: BASE_PATH
            value: "{{ .Values.ingress.path }}/"
          - name: APP_CONFIG_OAUTH2_REDIRECT_SILENT_IFRAME_URI
            value: "{{ .Values.ingress.path }}/assets/silent-refresh.html"
          - name: APP_CONFIG_OAUTH2_REDIRECT_LOGIN
            value: "{{ .Values.ingress.path }}"
          - name: APP_CONFIG_OAUTH2_REDIRECT_LOGOUT
            value: "{{ .Values.ingress.path }}"
          {{end}}
          {{- range $key, $val := .Values.env }}
          - name: {{ $key | quote }}
            value: {{ $val | quote }}
          {{- end }}
