{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "alfresco-adf-app.fullname" . }}
  labels:
    app: {{ template "alfresco-adf-app.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- include "common.ingress-annotations" . | indent 4 }}
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
spec:
  rules:
    {{- if and (include "common.ingress-host" .) (eq .Values.ingress.defaultHostNameEnabled true) }}
    - host: {{ template "common.ingress-host" . }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: {{ include "common.ingress-path" . }}{{- if ne (include "common.ingress-path" .) "/" }}/{{- end}}?(.*)
            backend:
              serviceName: {{ template "alfresco-adf-app.fullname" . }}
              servicePort: {{ .Values.service.port }}
  {{- if include "common.ingress-tls" . }}
  tls:
  - secretName: {{ template "common.ingress-tlssecretname" . }}
    {{- if (include "common.ingress-host" .) }}
    hosts:
    - {{ template "common.ingress-host" . }}
    {{- end }}
  {{- end }}
{{- end }}
