apiVersion: v1
name: alfresco-adf-app
description: A Helm chart for a generic Alfresco ADF frontend application
version: 2.1.3
appVersion: 2.1.0
keywords:
  - alfresco
  - adf
  - alfresco development framework
  - content
  - content services
  - alfresco content services
  - process
  - process services
  - alfresco process services
  - activiti
  - activiti enterprise
  - alfresco activiti enterprise
home: https://www.alfresco.com
maintainers:
  - name: Alfresco
sources:
  - https://git.alfresco.com/process-services-public/alfresco-adf-app-deployment
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
