replicaCount: 1
registryPullSecrets: quay-registry-secret

image:
  repository: quay.io/alfresco/alfresco-adf-app
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: adf-app
  type: ClusterIP
  port: 80
ingress:
  path: /
