replicaCount: 1
registryPullSecrets: quay-registry-secret

adminApp:
  replicacount: 1
  image:
    repository: quay.io/alfresco/alfresco-process-admin
    tag: "develop"
    pullPolicy: IfNotPresent
    internalPort: 3000
  service:
    name: adf-admin
    type: NodePort
    nodePort: 3000
  ingress:
    path: /apa-app

modelerApp:
  replicacount: 1
  image:
    repository: quay.io/alfresco/alfresco-modeler-app
    tag: "develop"
    pullPolicy: IfNotPresent
    internalPort: 80
  service:
    name: adf-modeler
    type: NodePort
    nodePort: 80
  ingress:
    path: /ama-app



